version: "3.6"
  
services:
  data:
    image: mysql:8
    container_name : mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=spring
    ports:
      - 3306:3306
      
  app:
    container_name: boot
    build: ./application/spring
   # restart: on-failure
    depends_on:
      - data
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/room?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring
    volumes:
      - ./application/spring:/usr/app
      - ./application/spring/log:/usr/app/log
