version: "3.6"
  
services:
  mysqldb:
    image: mysql:8
    container_name : mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_USER=toto
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=room
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysqldb
    networks:
      - room-mysql
  
  spring:
    container_name: boot
    
    build: ./application/spring
    #restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/room?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: toto
      SPRING_DATASOURCE_PASSWORD: toor
    volumes:
      - ./application/spring:/usr/app
    stdin_open: true
    tty: true
    networks:
      - room-mysql

networks:
  room-mysql:

volumes:
  db:
